version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.28
    commands:
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  pre_build:
    commands:
      - echo "Setting up kubeconfig with IAM token"
      - aws eks update-kubeconfig --region us-east-1 --name hilarious-pop-dinosaur
      - export KUBECONFIG=/root/.kube/config
  build:
    commands:
      - echo "Deploying with Helm"
      - helm upgrade --install nginx-demo . --wait
