version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.28
    commands:
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  pre_build:
    commands:
      - echo "Setting up KUBECONFIG"
      - aws eks update-kubeconfig --region us-east-1 --name hilarious-pop-dinosaur
  build:
    commands:
      - echo "Deploying with Helm"
      - helm upgrade --install helm . --namespace default --create-namespace
