version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Helm...
      - curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - echo Installing kubectl using yum...
      - yum install -y curl unzip
      - curl -o /etc/yum.repos.d/eks.repo https://amazon-eks.s3.us-west-2.amazonaws.com/eks/1.28.2/2023-10-03/eks.repo
      - yum install -y kubectl

  pre_build:
    commands:
      - echo Logging in to Amazon EKS cluster...
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region us-east-1 --name hilarious-pop-dinosaur
      - kubectl version --client
      - kubectl get nodes

  build:
    commands:
      - echo Deploying with Helm...
      - helm upgrade --install nginx-demo . --namespace default --create-namespace

artifacts:
  files:
    - '**/*'
